export const STRIPE_MODULE_OPTIONS = 'STRIPE_MODULE_OPTIONS'
// export const STRIPE_WEBHOOK_SERVICE = 'STRIPE_WEBHOOK_SERVICE'
export const STRIPE_EVENT_KEY = 'STRIPE_EVENT_KEY'
export const STRIPE_CLIENT = 'STRIPE_CLIENT'
