version: '3.8'

# @starter revise per project requirements
# @starter update the `image` and `container_name` in the api service below
# @starter uncomment and edit postgres, redis, and adminer-related properties if/as required

services:
  api:
    image: starter/project-api
    container_name: starter-project-api
    build:
      context: .
      # target: development
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # host_port:container_port
      - ${PORT}:${PORT}
      # - 9229:9229 # debug port
    # command: dumb-init yarn start:prod
    command: dumb-init node dist/main
    env_file:
      - .env
    networks:
      - appnet
    restart: unless-stopped

    # @starter - consider common additional properties for the api service --
    # environment:
    #   - NODE_ENV=production
    #   - VERSION=1.0
    # depends_on:
    #   - redis
    #   - postgres
    # links:
    #   - postgres:postgres

  # redis:
  #   container_name: redis
  #   image: redis:5
  #   networks:
  #     - appnet

  # postgres:
  #   container_name: postgres
  #   image: postgres:12
  #   networks:
  #     - appnet
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #     PG_DATA: /var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #       - 8080:8080

networks:
  appnet:

# volumes:
#   pgdata:
